### ISSUE TITLE
Output ChatGPT Response

### ISSUE THREAD

**Issue by erwilliams64** [quayside-app/quayside_mvp#17]
Explore ChatGPT function calling, turn ChatGPT response into indexed tasks, display ChatGPT tasks as a tree

**Comment by eleonora-sc** [comment]
Plan:
1. User inputs a prompt
2. Prompt gets parsed by 1. 2. 3. 4. .... etc
3. TODO: subprompts become new chatgpt api calls
4. TODO: store all tasks and subtasks, display them
