### ISSUE TITLE
Integrate ChatGPT

### ISSUE THREAD

**Issue by schromya** [quayside-app/quayside_mvp#3]
Use the ChatGPT API to integrate ChatGPT into the front end. Let the user enter the API key and a project topic. It should produce broken down X number of tasks. Use ChatGPT function integration ([here](https://semaphoreci.com/blog/function-calling#:~:text=OpenAI%2C%20the%20company%20behind%20ChatGPT,possibilities%20for%20AI%2Dpowered%20applications.) and [here](https://platform.openai.com/docs/guides/gpt/function-calling)). Remember to make this modular so that we sub in other LLMs.

**Comment by schromya** [comment]
Mya will apply for ChatGPT 4.

**Comment by eleonora-sc** [comment]
What got accomplished:
1.  Using the OpenAI library, we send an API call with a POST request (in src > app > chat-gpt > route.js
2. To the API call, we pass the userPrompt and the apiKey from user input text fields in NewProjectModal
